/**
 * npm run cut: bake every art SVG into cut geometry (architecture.md §7.4).
 *   src/sections/<station>/art/*.svg, src/scene/worker/art/*.svg → <name>.cut.json next to the source
 *   src/ui/art/*.svg → src/ui/clips.generated.css
 * `--check` writes nothing and fails if any generated file is stale (CI freshness).
 * Lint failures always fail.
 */
import { globSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { parseSvg } from "./parse.mts";
import { cutFile, clipCss } from "./emit.mts";
import { SCENE, UI } from "./wobble.mts";

const root = join(import.meta.dirname, "../..");
const check = process.argv.includes("--check");
const errors: string[] = [];
const stale: string[] = [];

function write(path: string, content: string) {
  const prev = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (prev === content) return;
  if (check) stale.push(path);
  else writeFileSync(path, content);
}

const sceneFiles = [
  ...globSync("src/sections/*/art/*.svg", { cwd: root }),
  ...globSync("src/scene/worker/art/*.svg", { cwd: root }),
].sort();

for (const rel of sceneFiles) {
  const src = parseSvg(rel, readFileSync(join(root, rel), "utf8"));
  const name = basename(rel, ".svg");
  const registration = rel.includes("worker") ? "exact" : "hand";
  const { out, errors: e } = cutFile(src, name, SCENE, { registration });
  errors.push(...e);
  write(join(root, dirname(rel), `${name}.cut.json`), JSON.stringify(out) + "\n");
  const pts = out.sheets.reduce((a, s) => a + s.pieces.reduce((b, p) => b + p.outer.length / 2 + p.holes.reduce((c, h) => c + h.length / 2, 0), 0), 0);
  console.log(`cut  ${rel}  ${out.sheets.length} sheets, ${pts} points`);
}

const uiFiles = globSync("src/ui/art/*.svg", { cwd: root }).sort();
const css: string[] = [];
for (const rel of uiFiles) {
  const src = parseSvg(rel, readFileSync(join(root, rel), "utf8"), { flipY: false });
  const { css: lines, errors: e } = clipCss(src, UI);
  errors.push(...e);
  css.push(...lines);
  console.log(`clip ${rel}  ${lines.length} shapes`);
}
write(
  join(root, "src/ui/clips.generated.css"),
  `/* generated by scripts/cut from src/ui/art: do not edit */\n:root {\n${css.join("\n")}\n}\n`,
);

if (errors.length) {
  console.error(`\n${errors.length} lint error(s):\n  ${errors.join("\n  ")}`);
  process.exit(1);
}
if (stale.length) {
  console.error(`\nstale generated files (run npm run cut):\n  ${stale.join("\n  ")}`);
  process.exit(1);
}
